dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - jupyter_contrib_nbextensions 
    - jupyter_contrib_nbextensions --user
